### ISSUE TITLE
Fix Ubuntu 12.04 build

### ISSUE THREAD

**Issue by ygrange** [ygrange/lofar-profiling#9]
Testing routine on Ubuntu 12.04 build fails. More investigation needed.

**Comment by ygrange** [comment]
Tried running the test again. Retried the build and now it builds. The test that failed was:
	121 - tFFTCMatrix (SEGFAULT)

**Comment by tammojan** [comment]
No, haven't seen it failing before. You say it now builds, but does the test still fail?

**Comment by tammojan** [comment]
Wouldn't a great use case of the images be that you can give me one (and tell me how to open it), then I can mess around in it (install valgrind or gdb) and find the bug?

It's most likely an environment problem but if cmake didn't catch it if say it's a bug.

**Comment by ygrange** [comment]
Seems not very reproducible. Closing.
